"""
Suggestion Generator Agent - Analyzes resume gaps and generates AI-powered
improvement suggestions prioritized by impact.
"""
from typing import Any, TypedDict

from langchain_aws import ChatBedrockConverse
from langchain_core.messages import SystemMessage, HumanMessage
from langgraph.graph import StateGraph, END
from pydantic import BaseModel, Field

from api.config import settings
from .base import BaseAgent

# ---------------------------------------------------------------------------
# Pydantic models for structured LLM output
# ---------------------------------------------------------------------------


class Gap(BaseModel):
    """A single gap identified between resume and job requirements."""

    category: str = Field(
        description="Gap category: 'missing_skill', 'weak_experience', "
        "'missing_qualification', 'formatting', 'content_quality'",
    )
    description: str = Field(
        description="Clear description of what is missing or weak",
    )
    job_requirement: str = Field(
        default="",
        description="The specific job requirement this gap relates to",
    )
    severity: str = Field(
        default="medium",
        description="How critical: 'high', 'medium', or 'low'",
    )


class GapAnalysis(BaseModel):
    """Complete gap analysis between resume and job description."""

    gaps: list[Gap] = Field(default_factory=list)
    strengths: list[str] = Field(
        default_factory=list,
        description="Areas where the resume already aligns well with the job",
    )
    overall_alignment: float = Field(
        ge=0.0,
        le=1.0,
        default=0.0,
        description="Overall alignment score between 0.0 and 1.0",
    )


class Suggestion(BaseModel):
    """A single actionable improvement suggestion."""

    section: str = Field(
        description="Resume section to improve: 'summary', 'experience', "
        "'skills', 'education', 'projects', 'certifications', 'formatting', 'general'",
    )
    suggestion: str = Field(
        description="The specific improvement recommendation",
    )
    example: str = Field(
        default="",
        description="A concrete example of how to implement the suggestion",
    )
    gap_addressed: str = Field(
        default="",
        description="Which gap this suggestion addresses",
    )
    impact: str = Field(
        default="medium",
        description="Expected impact: 'high', 'medium', or 'low'",
    )


class SuggestionList(BaseModel):
    """Collection of suggestions generated by the LLM."""

    suggestions: list[Suggestion] = Field(default_factory=list)


class PrioritizedSuggestions(BaseModel):
    """Suggestions reordered and scored by priority."""

    ranked_suggestions: list[Suggestion] = Field(default_factory=list)
    priority_areas: list[str] = Field(
        default_factory=list,
        description="Top areas the candidate should focus on, in priority order",
    )


# ---------------------------------------------------------------------------
# State
# ---------------------------------------------------------------------------


class SuggestionState(TypedDict):
    """State for suggestion generator agent."""

    request_id: str
    resume_data: dict
    job_description: str

    # Populated by analyze_gaps
    gap_analysis: dict

    # Populated by generate_suggestions
    suggestions: list[dict]

    # Populated by prioritize
    priority_areas: list[str]

    status: str
    error: str | None


# ---------------------------------------------------------------------------
# Agent
# ---------------------------------------------------------------------------


class SuggestionGeneratorAgent(BaseAgent):
    """Agent responsible for generating improvement suggestions."""

    def __init__(self) -> None:
        super().__init__("suggestion_generator")
        self.llm = ChatBedrockConverse(
            model="us.anthropic.claude-sonnet-4-20250514-v1:0",
            temperature=0.3,
            region_name=settings.aws_region,
            max_tokens=4096,
        )

    # ------------------------------------------------------------------
    # Graph construction
    # ------------------------------------------------------------------

    def build_graph(self) -> StateGraph:
        """Build the suggestion generator graph."""
        workflow = StateGraph(SuggestionState)

        workflow.add_node("analyze_gaps", self.analyze_gaps)
        workflow.add_node("generate_suggestions", self.generate_suggestions)
        workflow.add_node("prioritize", self.prioritize)

        workflow.set_entry_point("analyze_gaps")
        workflow.add_conditional_edges(
            "analyze_gaps",
            self._check_error,
            {"continue": "generate_suggestions", "error": END},
        )
        workflow.add_conditional_edges(
            "generate_suggestions",
            self._check_error,
            {"continue": "prioritize", "error": END},
        )
        workflow.add_edge("prioritize", END)

        return workflow

    def _check_error(self, state: SuggestionState) -> str:
        """Route to END on error, otherwise continue to the next node."""
        if state.get("error"):
            return "error"
        return "continue"

    # ------------------------------------------------------------------
    # Node: analyze_gaps
    # ------------------------------------------------------------------

    async def analyze_gaps(self, state: SuggestionState) -> dict:
        """Analyze gaps between resume and job requirements using LLM."""
        try:
            resume_data = state["resume_data"]
            job_description = state["job_description"]

            resume_text = self._flatten_resume_text(resume_data)

            structured_llm = self.llm.with_structured_output(GapAnalysis)

            result: GapAnalysis = await structured_llm.ainvoke([
                SystemMessage(
                    content=(
                        "You are an expert career coach and resume analyst. "
                        "Compare the candidate's resume against the job description "
                        "and identify all gaps. For each gap, categorize it as one of:\n"
                        "- 'missing_skill': A required skill not present in the resume\n"
                        "- 'weak_experience': Experience exists but is insufficient or "
                        "poorly described\n"
                        "- 'missing_qualification': A required degree, certification, "
                        "or credential not listed\n"
                        "- 'formatting': Structural or formatting improvements needed\n"
                        "- 'content_quality': Existing content that could be strengthened\n\n"
                        "Also identify strengths where the resume already aligns well. "
                        "Be thorough but fair — only flag genuine gaps."
                    )
                ),
                HumanMessage(
                    content=(
                        f"Resume:\n{resume_text}\n\n"
                        f"Job Description:\n{job_description}"
                    )
                ),
            ])

            return {
                "status": "analyzing_gaps",
                "gap_analysis": result.model_dump(),
            }

        except Exception as e:
            return {
                "status": "error",
                "error": f"Gap analysis failed: {e}",
            }

    # ------------------------------------------------------------------
    # Node: generate_suggestions
    # ------------------------------------------------------------------

    async def generate_suggestions(self, state: SuggestionState) -> dict:
        """Generate actionable improvement suggestions for each identified gap."""
        if state.get("error"):
            return {}

        try:
            gap_analysis = GapAnalysis(**state["gap_analysis"])
            resume_data = state["resume_data"]
            resume_text = self._flatten_resume_text(resume_data)

            if not gap_analysis.gaps:
                return {
                    "status": "generating",
                    "suggestions": [],
                }

            gaps_str = "\n".join(
                f"- [{gap.severity.upper()}] ({gap.category}) {gap.description}"
                for gap in gap_analysis.gaps
            )

            structured_llm = self.llm.with_structured_output(SuggestionList)

            result: SuggestionList = await structured_llm.ainvoke([
                SystemMessage(
                    content=(
                        "You are an expert resume writer and career coach. "
                        "Generate specific, actionable suggestions to improve the resume "
                        "based on the identified gaps. Rules:\n"
                        "1. Each suggestion must be concrete and implementable.\n"
                        "2. Provide a realistic example showing how to apply each suggestion.\n"
                        "3. Do NOT suggest fabricating experience or skills.\n"
                        "4. DO suggest rephrasing existing content to better highlight "
                        "relevant experience.\n"
                        "5. DO suggest adding quantifiable metrics where possible.\n"
                        "6. DO suggest reordering or restructuring sections for impact.\n"
                        "7. Assign impact level: 'high' for suggestions addressing critical "
                        "job requirements, 'medium' for nice-to-haves, 'low' for polish.\n"
                        "8. Generate at least one suggestion per high-severity gap."
                    )
                ),
                HumanMessage(
                    content=(
                        f"Resume:\n{resume_text}\n\n"
                        f"Job Description:\n{state['job_description']}\n\n"
                        f"Identified Gaps:\n{gaps_str}\n\n"
                        f"Strengths (preserve these):\n"
                        f"{', '.join(gap_analysis.strengths) if gap_analysis.strengths else 'None identified'}"
                    )
                ),
            ])

            return {
                "status": "generating",
                "suggestions": [s.model_dump() for s in result.suggestions],
            }

        except Exception as e:
            return {
                "status": "error",
                "error": f"Suggestion generation failed: {e}",
            }

    # ------------------------------------------------------------------
    # Node: prioritize
    # ------------------------------------------------------------------

    async def prioritize(self, state: SuggestionState) -> dict:
        """Prioritize suggestions by impact and return ranked results."""
        if state.get("error"):
            return {}

        try:
            suggestions = [Suggestion(**s) for s in state.get("suggestions", [])]

            if not suggestions:
                return {
                    "status": "completed",
                    "suggestions": [],
                    "priority_areas": [],
                }

            structured_llm = self.llm.with_structured_output(PrioritizedSuggestions)

            suggestions_str = "\n".join(
                f"- [{s.impact.upper()}] ({s.section}) {s.suggestion}"
                for s in suggestions
            )

            result: PrioritizedSuggestions = await structured_llm.ainvoke([
                SystemMessage(
                    content=(
                        "You are an expert career strategist. Reorder the following "
                        "resume improvement suggestions by priority. Consider:\n"
                        "1. High-impact suggestions addressing core job requirements first.\n"
                        "2. Quick wins that are easy to implement but effective.\n"
                        "3. Suggestions that improve multiple areas at once.\n"
                        "4. Lower-priority polish items last.\n\n"
                        "Also identify the top 3-5 priority areas the candidate should "
                        "focus on (e.g., 'Add cloud experience details', "
                        "'Quantify achievements')."
                    )
                ),
                HumanMessage(
                    content=f"Suggestions to prioritize:\n{suggestions_str}"
                ),
            ])

            return {
                "status": "completed",
                "suggestions": [s.model_dump() for s in result.ranked_suggestions],
                "priority_areas": result.priority_areas,
            }

        except Exception as e:
            return {
                "status": "error",
                "error": f"Prioritization failed: {e}",
            }

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _flatten_resume_text(resume_data: dict) -> str:
        """Recursively flatten resume_data into a single readable string."""
        parts: list[str] = []

        def _recurse(obj: Any) -> None:
            if isinstance(obj, str):
                parts.append(obj)
            elif isinstance(obj, list):
                for item in obj:
                    _recurse(item)
            elif isinstance(obj, dict):
                for value in obj.values():
                    _recurse(value)

        _recurse(resume_data)
        return " ".join(parts)
